# 4. Bank_Churnrate_Preprocess_and_Training<a id='2_Data_wrangling'></a>

## 4.1 Table of Contents<a id='2.1_Contents'></a>
* 4. Bank_Churnrate_Preprocess_and_Training
  * 4.1 Table of Contents
  * 4.2 Introduction
  * 4.3 Imports
  * 4.4 Load Bank Churn Missing and Dropped Datasets
  * 4.5 Create Train_Test Split & Preprocess Training Data
    * 4.5.1 Number & Handling Of Missing Values 
    * 4.5.2 Determing Correlation of Features with Target Feature ("Attrition_Flag")
      * 4.5.2.1 Determine User Base Churn vs. Not Churned
      * 4.5.2.2 One-Hot Encoding & Correlation with Categorical Features
  * 4.6 Save Data
  * 4.7 Summary


## 4.2 Introduction

Now that a thorough analysis as well as further cleaning and One-Hot enconding steps were implemented in prior EDA, train and test sets based on a usual 70/30 split will be created based on both the missing and dropped bank churn datasets for future steps in assessing model performance.

## 4.3 Imports<a id='2.3_Imports'></a>

Importing all appropriate packages in order to develop associated train and test sets for both imputed and dropped datasets for bank churn rate.

In [70]:
#Import pandas, matplotlib.pyplot, seaborn, and associated scikit learn methods and functions as well as random number for reproducibility
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
random_number = 42

## 4.4 Load Bank Churn Missing and Dropped Datasets

In [71]:
#Loading associated datasets of dropped vs. missing datasets for bank churn rate.
path_missing = 'C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/bank_data_train_preprocessed_missing.csv'
path_dropped = 'C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/bank_data_train_preprocessed_dropped.csv'
bank_missing_df = pd.read_csv(path_missing, index_col=0)
bank_dropped_df = pd.read_csv(path_dropped, index_col=0)

Auditing the datasets with .info() and .head() displaying the first few records.

In [72]:
#.info() on bank_missing_df and bank_dropped_df to see a summary of the data
bank_missing_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8101 entries, 0 to 8100
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Customer_Age                    8101 non-null   int64  
 1   Dependent_count                 8101 non-null   int64  
 2   Months_on_book                  8101 non-null   int64  
 3   Total_Relationship_Count        8101 non-null   int64  
 4   Months_Inactive_12_mon          8101 non-null   int64  
 5   Contacts_Count_12_mon           8101 non-null   int64  
 6   Credit_Limit                    8101 non-null   float64
 7   Total_Revolving_Bal             8101 non-null   int64  
 8   Avg_Open_To_Buy                 8101 non-null   float64
 9   Total_Amt_Chng_Q4_Q1            8101 non-null   float64
 10  Total_Trans_Amt                 8101 non-null   int64  
 11  Total_Trans_Ct                  8101 non-null   int64  
 12  Total_Ct_Chng_Q4_Q1             81

In [73]:
bank_dropped_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5690 entries, 3 to 8100
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Customer_Age                    5690 non-null   int64  
 1   Dependent_count                 5690 non-null   int64  
 2   Months_on_book                  5690 non-null   int64  
 3   Total_Relationship_Count        5690 non-null   int64  
 4   Months_Inactive_12_mon          5690 non-null   int64  
 5   Contacts_Count_12_mon           5690 non-null   int64  
 6   Credit_Limit                    5690 non-null   float64
 7   Total_Revolving_Bal             5690 non-null   int64  
 8   Avg_Open_To_Buy                 5690 non-null   float64
 9   Total_Amt_Chng_Q4_Q1            5690 non-null   float64
 10  Total_Trans_Amt                 5690 non-null   int64  
 11  Total_Trans_Ct                  5690 non-null   int64  
 12  Total_Ct_Chng_Q4_Q1             56

In [74]:
#head method on bank_missing_df and bank_dropped_df to print the first several rows of the data
bank_missing_df.head()

Customer_Age  Dependent_count  Months_on_book  Total_Relationship_Count  \
0            54                1              36                         1   
1            58                4              48                         1   
2            45                4              36                         6   
3            34                2              36                         4   
4            49                2              39                         5   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                       3                      3        3723.0   
1                       4                      3        5396.0   
2                       1                      3       15987.0   
3                       3                      4        3625.0   
4                       3                      4        2720.0   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  ...  \
0                 1728           1995.0                 0.595  ...   
1                 1803           3593.0                 0.493  ...   
2                 1648          14339.0                 0.732  ...   
3                 2517           1108.0                 1.158  ...   
4                 1926            794.0                 0.602  ...   

   Income_Category_$120K +  Income_Category_$40K - $60K  \
0                        0                            0   
1                        0                            0   
2                        0                            0   
3                        0                            0   
4                        0                            1   

   Income_Category_$60K - $80K  Income_Category_$80K - $120K  \
0                            0                             0   
1                            0                             0   
2                            0                             0   
3                            0                             0   
4                            0                             0   

   Income_Category_Less than $40K  Income_Category_missing  \
0                               0                        1   
1                               0                        1   
2                               1                        0   
3                               1                        0   
4                               0                        0   

   Card_Category_Blue  Card_Category_Gold  Card_Category_Platinum  \
0                   1                   0                       0   
1                   1                   0                       0   
2                   0                   1                       0   
3                   1                   0                       0   
4                   1                   0                       0   

   Card_Category_Silver  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 38 columns]

In [75]:
bank_dropped_df.head()

Customer_Age  Dependent_count  Months_on_book  Total_Relationship_Count  \
3            34                2              36                         4   
4            49                2              39                         5   
5            60                0              45                         5   
8            30                0              36                         3   
9            33                3              36                         5   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
3                       3                      4        3625.0   
4                       3                      4        2720.0   
5                       2                      4        1438.3   
8                       3                      2        2550.0   
9                       2                      3        1457.0   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  ...  \
3                 2517           1108.0                 1.158  ...   
4                 1926            794.0                 0.602  ...   
5                  648            790.3                 0.477  ...   
8                 1623            927.0                 0.650  ...   
9                    0           1457.0                 0.677  ...   

   Marital_Status_Single  Income_Category_$120K +  \
3                      1                        0   
4                      0                        0   
5                      0                        0   
8                      0                        0   
9                      1                        0   

   Income_Category_$40K - $60K  Income_Category_$60K - $80K  \
3                            0                            0   
4                            1                            0   
5                            0                            0   
8                            0                            0   
9                            0                            0   

   Income_Category_$80K - $120K  Income_Category_Less than $40K  \
3                             0                               1   
4                             0                               0   
5                             0                               1   
8                             0                               1   
9                             0                               1   

   Card_Category_Blue  Card_Category_Gold  Card_Category_Platinum  \
3                   1                   0                       0   
4                   1                   0                       0   
5                   1                   0                       0   
8                   1                   0                       0   
9                   1                   0                       0   

   Card_Category_Silver  
3                     0  
4                     0  
5                     0  
8                     0  
9                     0  

[5 rows x 35 columns]

In [76]:
bank_missing_df.shape

(8101, 38)

In [77]:
bank_dropped_df.shape

(5690, 35)

## 4.5 Create Train_Test Split & Preprocess Training Data

### 4.5.1 Create Train_Test_Split

For implementation of future modeling, a train_test_split is created for both the missing and dropped datasets. The test size is arbritraily set for a 70/30 split.

In [78]:
#Creating train_test_split for both missing and dropped bank churn datasets.
#Test size arbritarily set at 70/30 split for training and future model performance and testing.

X_missing = bank_missing_df.drop(['Attrition_Flag'], axis=1)
y_missing = bank_missing_df['Attrition_Flag']
X_dropped = bank_dropped_df.drop(['Attrition_Flag'], axis=1)
y_dropped = bank_dropped_df['Attrition_Flag']


X_train_missing, X_test_missing, y_train_missing, y_test_missing = train_test_split(X_missing, y_missing, test_size=0.30, random_state = random_number) 
X_train_dropped, X_test_dropped, y_train_dropped, y_test_dropped = train_test_split(X_dropped, y_dropped, test_size=0.30, random_state= random_number)

### 4.5.2 Apply StandardScaler() for Training Data

In order to create equal distributions with mean centered at 0 between each of the features for future modeling, a standard scaler object is created and defined for training for both datasets. The same scaler is also applied for transforming X_test datasets for consistency and future modeling.

In [79]:
# Created function for fitting and transforming scaler object for X_train of both datasets and then transform X_test for both datasets
def scaling(train , test):
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(train)
    X_test_scaled = scaler.transform(test)
    
    return X_train_scaled, X_test_scaled

In [80]:
X_train_scaled_missing , X_test_scaled_missing = scaling(X_train_missing, X_test_missing)

In [81]:
X_train_scaled_dropped , X_test_scaled_dropped = scaling(X_train_dropped, X_test_dropped)

Reviewing as well the above arrays created after scaling the trained datasets.

In [82]:
#Reviewing of X_train_scaled_missing and dropped as well as X_test_scaled_missing and dropped
X_train_scaled_missing

array([[-0.41349078,  1.28797953, -1.35293228, ..., -0.11017496,
        -0.04408862, -0.24090084],
       [ 1.45572316, -1.03949649,  0.0039595 , ..., -0.11017496,
        -0.04408862, -0.24090084],
       [ 0.33419479,  1.28797953, -0.85951709, ..., -0.11017496,
        -0.04408862, -0.24090084],
       ...,
       [ 0.08496627,  2.06380487,  0.6207285 , ..., -0.11017496,
        -0.04408862, -0.24090084],
       [ 0.08496627,  0.51215419,  0.8674361 , ..., -0.11017496,
        -0.04408862, -0.24090084],
       [ 1.58033743, -1.03949649,  2.10097409, ..., -0.11017496,
        -0.04408862, -0.24090084]])

In [83]:
X_test_scaled_missing

array([[ 1.33110890e+00, -2.63671151e-01,  3.95950466e-03, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01],
       [-4.13490784e-01,  1.28797953e+00, -2.42748093e-01, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01],
       [-1.90886194e+00, -1.03949649e+00, -1.72299368e+00, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01],
       ...,
       [-2.88876521e-01, -1.03949649e+00, -2.42748093e-01, ...,
        -1.10174961e-01, -4.40886190e-02,  4.15108555e+00],
       [ 2.09580531e-01,  5.12154188e-01, -7.36163289e-01, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01],
       [ 3.34194794e-01,  1.28797953e+00,  8.67436097e-01, ...,
        -1.10174961e-01, -4.40886190e-02, -2.40900841e-01]])

In [84]:
X_train_scaled_dropped

array([[-1.50889427,  0.52736863, -0.98537568, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [-0.63893519, -1.02914063, -0.48336093, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [ 0.35530376,  2.08387789, -0.10684986, ...,  9.5722467 ,
        -0.03884166, -0.23532724],
       ...,
       [ 1.47382257,  1.30562326,  2.15221653, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [ 1.22526283, -1.02914063,  1.02268333, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [-1.50889427, -0.250886  , -2.86793101, ..., -0.10446868,
        -0.03884166, -0.23532724]])

In [85]:
X_test_scaled_dropped

array([[-1.13605466,  1.30562326,  0.01865382, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [ 0.35530376,  1.30562326,  0.01865382, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [ 0.85242323,  0.52736863,  1.3991944 , ..., -0.10446868,
        -0.03884166, -0.23532724],
       ...,
       [-0.88749493, -0.250886  , -0.60886462, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [-0.26609559,  1.30562326, -0.73436831, ..., -0.10446868,
        -0.03884166, -0.23532724],
       [-1.26033453,  0.52736863,  0.01865382, ..., -0.10446868,
        -0.03884166, -0.23532724]])

Now that arrays have been created for X_train, X_test, y_train, and y_test for each missing and dropped datasets, these will be utilized in the next steps regarding assessing model performance.

## 4.6 Save data

In [91]:
#Missing X_train and y_train set shape
print(f"X_train_scaled_missing shape: {X_train_scaled_missing.shape} and y_train_missing shape: {y_train_missing.shape}")

X_train_scaled_missing shape: (5670, 37) and y_train_missing shape: (5670,)


In [92]:
#Missing X_test and y_test set shape
print(f"X_test_scaled_missing shape: {X_test_scaled_missing.shape} and y_test_missing shape: {y_test_missing.shape}")

X_test_scaled_missing shape: (2431, 37) and y_test_missing shape: (2431,)


In [94]:
#Dropped X_train and y_train set shape
print(f"X_train_scaled_dropped shape: {X_train_scaled_dropped.shape} and y_train_dropped shape: {y_train_dropped.shape}")

X_train_scaled_dropped shape: (3983, 34) and y_train_dropped shape: (3983,)


In [95]:
#Dropped X_test and y_test set shape
print(f"X_test_scaled_dropped shape: {X_test_scaled_dropped.shape} and y_test_dropped shape: {y_test_dropped.shape}")

X_test_scaled_dropped shape: (1707, 34) and y_test_dropped shape: (1707,)


In [111]:
# save the data to a new csv file
datapath = 'C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets'
bank_clean_drop_numeric.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/bank_data_train_preprocessed_dropped.csv') 
bank_clean_numeric.to_csv('C:/Users/tpooz/OneDrive/Desktop/Data_Science_BootCamp_2023/SpringBoard_Github/Bank-Churnrate/0_Datasets/bank_data_train_preprocessed_missing.csv') 

## 3.7 Summary

After a further analysis and "cleaning" of the dataset from dropping NA columns and transforming non-numeric columns to numeric, feature values that have a moderate positive correlation with the target Attrition_Flag column are namely Total_Trans_Ct, Total_Ct_Chng_Q4_Q1, Total_Revolving_Bal, Avg_Utilization_Ratio, Total_Trans_Amt, Total_Relationship_Count, and Total_Amt_Chng_Q4_Q1 columns. And feature values with moderate negative correlation with Attrition_Flag column are namely Contacts_Count_12_mon and Months_Inactive_12_mon. Again there seems to be an intuitive sense to this, as based on the customers pattern of use, seems to correlate with whether or not the customer will attrite. Howevever, it seems that how many dependents a customer had or their relationship count, also had some affect on the variance for the Attrition_Flag column. These features will be kept in mind when in development of future steps for an appropraite predictive model. 

The above relationships were seen for both the datasets where the NA values were dropped vs. being imputed with 'missing' which means dropping the NA values in the columns did not seem to affect the overall correlation levels.

Viewing the datasets and target variable, this will be a classification learning problem so different classification models (Logistic Regression, Random Forest, Gradeint Booosting, etc.) will be cross-validated and assessed to determine an appropriate model for prediction.

Both datasets for values where the 'NA' values were dropped vs. NA values being imputed with missing were saved in order to be further analyzed and used to assess performance of next steps in developing a generalizable predictive model.